//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetEasySave.consoleApp.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings_fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_fr_FR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetEasySave.consoleApp.Ressources.strings.fr-FR", typeof(strings_fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de sauvegarde : {0} 1 - Sauvegarde Complète (default) {1} 2 - Sauvegarde Incrementielle.
        /// </summary>
        internal static string ChoiceBackup {
            get {
                return ResourceManager.GetString("ChoiceBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde Complète.
        /// </summary>
        internal static string FullBackup {
            get {
                return ResourceManager.GetString("FullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde Incrementielle.
        /// </summary>
        internal static string IncrBackup {
            get {
                return ResourceManager.GetString("IncrBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copie terminée, {0} fichiers copiés sur {1} de {2} vers {3}.
        /// </summary>
        internal static string MessageFull {
            get {
                return ResourceManager.GetString("MessageFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copie terminée, {0} fichiers modifiés sur {1} analysés..
        /// </summary>
        internal static string MessageIncr {
            get {
                return ResourceManager.GetString("MessageIncr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copie terminée, vos fichiers sont à jour, aucun fichier n&apos;a été modifié sur {0}.
        /// </summary>
        internal static string noFiles {
            get {
                return ResourceManager.GetString("noFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin de sauvegarde final :.
        /// </summary>
        internal static string PathDest {
            get {
                return ResourceManager.GetString("PathDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin de sauvegarde initial :.
        /// </summary>
        internal static string PathSource {
            get {
                return ResourceManager.GetString("PathSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre chemin initial ou de destination n&apos;existe pas..
        /// </summary>
        internal static string wrongPath {
            get {
                return ResourceManager.GetString("wrongPath", resourceCulture);
            }
        }
    }
}
