//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.consoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class langage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.consoleApp.Resources.langage", typeof(langage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check your SaveWork files and free up space..
        /// </summary>
        public static string checkYourFiles {
            get {
                return ResourceManager.GetString("checkYourFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the SaveWork :.
        /// </summary>
        public static string choseName {
            get {
                return ResourceManager.GetString("choseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a type for the SaveWork :.
        /// </summary>
        public static string choseType {
            get {
                return ResourceManager.GetString("choseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [Y] for creation, [Enter] for abandon....
        /// </summary>
        public static string confirmLine {
            get {
                return ResourceManager.GetString("confirmLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The copy of the files is completed..
        /// </summary>
        public static string copyCompleted {
            get {
                return ResourceManager.GetString("copyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove error(s) occurred....
        /// </summary>
        public static string deleteError {
            get {
                return ResourceManager.GetString("deleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a SaveWork for deletion :.
        /// </summary>
        public static string deletion {
            get {
                return ResourceManager.GetString("deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a destination path for the SaveWork :.
        /// </summary>
        public static string destPath {
            get {
                return ResourceManager.GetString("destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This SaveWork&apos;s destination path is :.
        /// </summary>
        public static string destPathSaveWork {
            get {
                return ResourceManager.GetString("destPathSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a SaveWork for execution :.
        /// </summary>
        public static string execution {
            get {
                return ResourceManager.GetString("execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a key to exit....
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of SaveWork files has been exceeded..
        /// </summary>
        public static string fullSaveWorks {
            get {
                return ResourceManager.GetString("fullSaveWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, please select an option:.
        /// </summary>
        public static string gretting {
            get {
                return ResourceManager.GetString("gretting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1] : Create a new SaveWork.
        /// </summary>
        public static string menu_choice1 {
            get {
                return ResourceManager.GetString("menu.choice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2] : Delete an existing SaveWork.
        /// </summary>
        public static string menu_choice2 {
            get {
                return ResourceManager.GetString("menu.choice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [3] : Launch a SaveWork.
        /// </summary>
        public static string menu_choice3 {
            get {
                return ResourceManager.GetString("menu.choice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [4] : Launch all the existing SaveWorks.
        /// </summary>
        public static string menu_choice4 {
            get {
                return ResourceManager.GetString("menu.choice4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [5] : List all the existing SaveWorks.
        /// </summary>
        public static string menu_choice5 {
            get {
                return ResourceManager.GetString("menu.choice5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This SaveWork&apos;s Name is :.
        /// </summary>
        public static string nameSaveWork {
            get {
                return ResourceManager.GetString("nameSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 2 requested.
        /// </summary>
        public static string option2 {
            get {
                return ResourceManager.GetString("option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 3 requested.
        /// </summary>
        public static string option3 {
            get {
                return ResourceManager.GetString("option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 4 requested.
        /// </summary>
        public static string option4 {
            get {
                return ResourceManager.GetString("option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential error(s) occured....
        /// </summary>
        public static string potentialError {
            get {
                return ResourceManager.GetString("potentialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to return to the menu....
        /// </summary>
        public static string pressKeyMenu {
            get {
                return ResourceManager.GetString("pressKeyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter [Y] for execution, [Enter] for abandon....
        /// </summary>
        public static string SequentialConfirm {
            get {
                return ResourceManager.GetString("SequentialConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequential copy of the files is completed..
        /// </summary>
        public static string sequentialCopyCompleted {
            get {
                return ResourceManager.GetString("sequentialCopyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to execute all saved SaveWorks ?.
        /// </summary>
        public static string SequentialValidation {
            get {
                return ResourceManager.GetString("SequentialValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a source path for the SaveWork :.
        /// </summary>
        public static string sourcePath {
            get {
                return ResourceManager.GetString("sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This SaveWork&apos;s source path is :.
        /// </summary>
        public static string sourcePathSaveWork {
            get {
                return ResourceManager.GetString("sourcePathSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1] : Complete.
        /// </summary>
        public static string typeComplete {
            get {
                return ResourceManager.GetString("typeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2] : Differential.
        /// </summary>
        public static string typeDiff {
            get {
                return ResourceManager.GetString("typeDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This SaveWork&apos;s type is :.
        /// </summary>
        public static string typeSaveWork {
            get {
                return ResourceManager.GetString("typeSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation step :.
        /// </summary>
        public static string validation {
            get {
                return ResourceManager.GetString("validation", resourceCulture);
            }
        }
    }
}
