//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.consoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class langage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langage() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.consoleApp.Resources.langage", typeof(langage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, check your SaveWork files and free up space..
        /// </summary>
        public static string checkYourFiles {
            get {
                return ResourceManager.GetString("checkYourFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a name for the SaveWork.
        /// </summary>
        public static string choseName {
            get {
                return ResourceManager.GetString("choseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a type for the SaveWork.
        /// </summary>
        public static string choseType {
            get {
                return ResourceManager.GetString("choseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press [Y] for creation, [Enter] for abandon....
        /// </summary>
        public static string confirmLine {
            get {
                return ResourceManager.GetString("confirmLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a destination path for the SaveWork.
        /// </summary>
        public static string destPath {
            get {
                return ResourceManager.GetString("destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The destination path of this SaveWork is :.
        /// </summary>
        public static string destPathSaveWork {
            get {
                return ResourceManager.GetString("destPathSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press a key for exit....
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The limit of SaveWork files has been exceeded..
        /// </summary>
        public static string fullSaveWorks {
            get {
                return ResourceManager.GetString("fullSaveWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hi, please select a choice:.
        /// </summary>
        public static string gretting {
            get {
                return ResourceManager.GetString("gretting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [1] : Create a new SaveWork.
        /// </summary>
        public static string menu_choice1 {
            get {
                return ResourceManager.GetString("menu.choice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [2] : Delete an existing SaveWork.
        /// </summary>
        public static string menu_choice2 {
            get {
                return ResourceManager.GetString("menu.choice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [3] : Launch a SaveWork.
        /// </summary>
        public static string menu_choice3 {
            get {
                return ResourceManager.GetString("menu.choice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [4] : Launch all the existings SaveWork.
        /// </summary>
        public static string menu_choice4 {
            get {
                return ResourceManager.GetString("menu.choice4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [5] : List all the existings SaveWork.
        /// </summary>
        public static string menu_choice5 {
            get {
                return ResourceManager.GetString("menu.choice5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The name of this SaveWork is :.
        /// </summary>
        public static string nameSaveWork {
            get {
                return ResourceManager.GetString("nameSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à He requested option 2.
        /// </summary>
        public static string option2 {
            get {
                return ResourceManager.GetString("option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à He requested option 3.
        /// </summary>
        public static string option3 {
            get {
                return ResourceManager.GetString("option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à He requested option 4.
        /// </summary>
        public static string option4 {
            get {
                return ResourceManager.GetString("option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a source path for the SaveWork.
        /// </summary>
        public static string sourcePath {
            get {
                return ResourceManager.GetString("sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source path of this SaveWork is :.
        /// </summary>
        public static string sourcePathSaveWork {
            get {
                return ResourceManager.GetString("sourcePathSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [1] : Complete.
        /// </summary>
        public static string typeComplete {
            get {
                return ResourceManager.GetString("typeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [2] : Differential.
        /// </summary>
        public static string typeDiff {
            get {
                return ResourceManager.GetString("typeDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The type of this SaveWork is :.
        /// </summary>
        public static string typeSaveWork {
            get {
                return ResourceManager.GetString("typeSaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation step:.
        /// </summary>
        public static string validation {
            get {
                return ResourceManager.GetString("validation", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à deletion:.
        /// </summary>
        public static string deletion
        {
            get
            {
                return ResourceManager.GetString("deletion", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à execution:.
        /// </summary>
        public static string execution
        {

            get
            {
                return ResourceManager.GetString("execution", resourceCulture);
            }
        }

        /// <summary>
        /// Recherche une chaîne localisée semblable à SequentialValidadtion.
        /// </summary>
        public static string SequentialValidation
        {
            get
            {
                return ResourceManager.GetString("SequentialValidation", resourceCulture);
            }
        }

        /// <summary>
        /// Recherche une chaîne localisée semblable à SequentialConfirm.
        /// </summary>
        public static string SequentialConfirm
        {
            get
            {
                return ResourceManager.GetString("SequentialConfirm", resourceCulture);
            }
        }
    }
}
